SELECT *
FROM APPS.XDO_DS_DEFINITIONS_B
WHERE DATA_SOURCE_CODE = 'BKR_AR_INV_PRINT_BR2491'

SELECT *
FROM APPS.XDO_DS_DEFINITIONS_VL
WHERE DATA_SOURCE_CODE = 'BKR_AR_INV_PRINT_BR2491'

SELECT *
FROM APPS.XDO_TEMPLATES_B
WHERE TEMPLATE_CODE =  'BKR_AR_INV_PRINT_BR2491'

SELECT *
FROM APPS.XDO_TEMPLATES_VL
WHERE TEMPLATE_CODE =  'BKR_AR_INV_PRINT_BR2491'

SELECT *
FROM APPS.XDO_LOBS
WHERE LOB_CODE =  'BKR_AR_INV_PRINT_BR2491'
