SELECT FCP.USER_CONCURRENT_PROGRAM_NAME,FCR.* 
FROM FND_CONCURRENT_PROGRAMS_VL FCP,
     FND_CONCURRENT_REQUESTS FCR
WHERE USER_CONCURRENT_PROGRAM_NAME IN ('BH AR E-Invoice Extract - Peru','BH Copy File Program')
AND FCP.CONCURRENT_PROGRAM_ID = FCR.CONCURRENT_PROGRAM_ID
/*
AND FCR.ARGUMENT3 IN (SELECT CUSTOMER_TRX_ID 
                      FROM RA_CUSTOMER_TRX_ALL
                      WHERE TRX_NUMBER IN ('20200542','20209509','20200543')
                      )
*/
AND FCR.REQUEST_ID >=   421226868                    


421226942



