SELECT USER_CONCURRENT_PROGRAM_NAME,CONCURRENT_PROGRAM_NAME,FE.EXECUTABLE_NAME,EXECUTION_FILE_NAME,FE.*
FROM FND_CONCURRENT_PROGRAMS_VL FCP,
     FND_EXECUTABLES FE
WHERE FCP.USER_CONCURRENT_PROGRAM_NAME LIKE 'PRC%'-- Program'
AND FCP.EXECUTABLE_ID = FE.EXECUTABLE_ID