(select HOU.NAME,FT.TERRITORY_CODE,FC.CURRENCY_CODE
from fnd_currencies FC,
     fnd_territories FT,
     XLE_ENTITY_PROFILES XEP,
     HR_OPERATING_UNITS HOU,
     HZ_GEOGRAPHIES HG
where HOU.ORGANIZATION_ID = 119771--FND_GLOBAL.ORG_ID
AND HOU.DEFAULT_LEGAL_CONTEXT_ID = XEP.LEGAL_ENTITY_ID
AND XEP.GEOGRAPHY_ID = HG.GEOGRAPHY_ID
AND HG.COUNTRY_CODE = FT.TERRITORY_CODE
AND FC.ISSUING_TERRITORY_CODE = FT.TERRITORY_CODE
AND FC.ENABLED_FLAG = 'Y'
AND TRUNC(SYSDATE) BETWEEN TRUNC(NVL(START_DATE_ACTIVE,SYSDATE -1)) AND TRUNC(NVL(END_DATE_ACTIVE,SYSDATE + 1))
AND ISO_FLAG = 'Y'    
AND FT.OBSOLETE_FLAG = 'N') LOCAL_CURR
