SELECT HOU.ORGANIZATION_ID,HOU.NAME,HP.PARTY_NAME "CUSTOMER_NAME",HCA.ACCOUNT_NUMBER "ACCOUNT_NUMBER",HCA.CUST_ACCOUNT_ID,HPS.PARTY_SITE_NUMBER "DUNS",HCU.SITE_USE_CODE,PRIMARY_FLAG,HCU.SITE_USE_ID
        FROM APPS.HZ_PARTIES HP,
             APPS.HZ_PARTY_SITES HPS,
             APPS.HZ_CUST_ACCOUNTS_ALL HCA,
             APPS.HZ_CUST_ACCT_SITES_ALL HCAS,
             APPS.HZ_CUST_SITE_USES_ALL HCU,
             APPS.HR_OPERATING_UNITS HOU
        WHERE HP.PARTY_ID = HCA.PARTY_ID
        AND  HCA.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID
        AND HP.PARTY_ID = HPS.PARTY_ID
        AND HCAS.CUST_ACCT_SITE_ID = HCU.CUST_ACCT_SITE_ID
        AND HOU.ORGANIZATION_ID = HCAS.ORG_ID
        AND HCAS.ORG_ID = HCU.ORG_ID
        AND HCAS.PARTY_SITE_ID = HPS.PARTY_SITE_ID
        AND HOU.NAME IN  ('OU_NP_IT')
        AND HCAS.STATUS = 'A'
        AND HCU.STATUS = 'A'
        AND HPS.STATUS = 'A'
        AND HP.STATUS = 'A'
        AND HCA.STATUS = 'A'
        AND SITE_USE_CODE = 'BILL_TO'
        AND HCU.SITE_USE_ID = 2799518