SELECT GS.AUTOPOST_SET_NAME,GO.LEDGER_ID,GO.LEDGER_NAME,GO.USER_JE_SOURCE_NAME,GO.USER_JE_CATEGORY_NAME,GO.ACTUAL_FLAG,GO.PERIOD_NAME
FROM GL_AUTOMATIC_POSTING_SETS_V GS,
     GL_AUTOMATIC_POSTING_OPTIONS_V GO
WHERE GS.AUTOPOST_SET_ID = GO.AUTOPOST_SET_ID
AND NVL(ENABLED_FLAG,'Y') = 'Y'
