SELECT DISTINCT GL.NAME,GJH.JE_HEADER_ID,GJH.NAME,GJH.CREATION_DATE,GJC.USER_JE_CATEGORY_NAME,GJS.USER_JE_SOURCE_NAME,FDS.NAME,GJH.DOC_SEQUENCE_VALUE,GJH.PERIOD_NAME,GJH.STATUS,GJL.*
FROM APPS.GL_JE_CATEGORIES GJC,
     APPS.GL_JE_SOURCES GJS, 
     APPS.GL_JE_HEADERS GJH, 
     APPS.GL_JE_LINES GJL, 
     APPS.GL_LEDGERS GL,
     APPS.FND_DOCUMENT_SEQUENCES FDS
WHERE GJH.JE_CATEGORY = GJC.JE_CATEGORY_NAME
AND GJH.JE_SOURCE = GJS.JE_SOURCE_NAME
AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
AND GJC.USER_JE_CATEGORY_NAME = 'FX ENTRY'
AND GJL.LEDGER_ID = GL.LEDGER_ID
AND GJH.DOC_SEQUENCE_ID = FDS.DOC_SEQUENCE_ID
ORDER BY GJH.JE_HEADER_ID DESC