SELECT  RCT.TRX_NUMBER,
        RCT.INVOICE_CURRENCY_CODE,
        BANK_ACCOUNT_NAME,
        BANK_ACCOUNT_NUM,
        CURRENCY_CODE,
        BANK_ACCOUNT_NUM_ELECTRONIC,
        AP_USE_ENABLE_FLAG,
        AR_USE_ENABLE_FLAG,
        AUTHORIZED_FLAG,
        BANK_HOME_COUNTRY,
        BANK_NAME,
        BANK_NUMBER,
        BANK_BRANCH_NAME,
        ADDRESS_LINE1,
        ADDRESS_LINE2,
        ADDRESS_LINE3,
        ADDRESS_LINE4,
        CITY,
        STATE,
        PROVINCE,
        ZIP,
        COUNTRY,
        BANK_BRANCH_TYPE,
        DESCRIPTION,
        EFT_SWIFT_CODE,
        EFT_USER_NUMBER
FROM
(SELECT HP_LE.PARTY_NAME OwnerOrg,
       XEP.LEGAL_ENTITY_IDENTIFIER OwnerLE,
       XEP.NAME OwnerLEName,
       hou.name OwnerOU,
       HOU.ORGANIZATION_ID,
       CBA.BANK_ACCOUNT_NAME,
       CBA.BANK_ACCOUNT_NUM,
       CBA.CURRENCY_CODE,
       CBA.BANK_ACCOUNT_NUM_ELECTRONIC,
       CBU.AP_USE_ENABLE_FLAG,
       CBU.AR_USE_ENABLE_FLAG,
       CBU.AUTHORIZED_FLAG,
       CBB.BANK_HOME_COUNTRY,
       CBB.BANK_NAME,
       CBB.BANK_NUMBER,
       CBB.BANK_BRANCH_NAME,
       CBB.ADDRESS_LINE1,
       CBB.ADDRESS_LINE2,
       CBB.ADDRESS_LINE3,
       CBB.ADDRESS_LINE4,
       CBB.CITY,
       CBB.STATE,
       CBB.PROVINCE,
       CBB.ZIP,
       CBB.COUNTRY,
       CBB.BANK_BRANCH_TYPE,
       CBB.DESCRIPTION,
       CBB.EFT_SWIFT_CODE,
       CBB.EFT_USER_NUMBER
FROM APPS.CE_BANK_ACCOUNTS CBA,
     APPS.CE_BANK_ACCT_USES_ALL CBU,
     APPS.HZ_PARTIES HP_LE,
     APPS.XLE_ENTITY_PROFILES XEP,
     APPS.HR_OPERATING_UNITS HOU,
     APPS.CE_BANK_BRANCHES_V CBB
WHERE CBA.BANK_ACCOUNT_ID = CBU.BANK_ACCOUNT_ID
AND   CBA.ACCOUNT_OWNER_ORG_ID = XEP.LEGAL_ENTITY_ID(+)
AND   ACCOUNT_OWNER_PARTY_ID = HP_LE.PARTY_ID(+)
AND HOU.ORGANIZATION_ID = CBU.ORG_ID
AND CBB.BANK_PARTY_ID = CBA.BANK_ID
AND CBB.BRANCH_PARTY_ID = CBA.BANK_BRANCH_ID
AND NVL(CBU.AR_USE_ENABLE_FLAG,'N') = 'Y'
AND TRUNC(SYSDATE) BETWEEN TRUNC(NVL(CBA.START_DATE,SYSDATE-1)) AND TRUNC(NVL(CBA.END_DATE,SYSDATE+1))) BANK,
APPS.RA_CUSTOMER_TRX_ALL RCT
WHERE RCT.ORG_ID = BANK.ORGANIZATION_ID
AND RCT.ORG_ID = 120511
AND RCT.INVOICE_CURRENCY_CODE = BANK.CURRENCY_CODE
