
SELECT * 
FROM ORG_ORGANIZATION_DEFINITIONS
WHERE OPERATING_UNIT = 118813

Master Org  Inventory Organization Code Segment1  Description Inventory Item Status Code  Item Type Enabled Flag 
Purchasing Item Flag Shippable Item Flag   Customer Order Flag   Internal Order Flag Service Item Flag Inventory Item Flag Inventory Asset Flag 
Default Include In Rollup Flag   Costing Enabled Flag   Cogs Account  Purchasing Enabled Flag  Customer Order Enabled Flag Internal Order Enabled Flag 
SO Transactions Flag  Mtl Transactions Enabled Flag Stock Enabled Flag Bom Enabled Flag   Build In WIP Flag Revision Qty Control Code 
Returnable Flag Allow Item Desc Update Flag Inspection Required Flag  Receipt Required Flag RFQ Required flag List Price Per Unit Price Tolerance Percent
Rounding Factor Lot Control Code  STARTING_PREFIX Starting Number Maturity Days Hold Days Lot Split Enabled Lot Translate Enabled Lot Divisible Lot Merge Enabled 
Lot Substitution Enable Bulk Picked Shelf Life Control Code Shelf Life Days Serial Number Control Code  Source Type Restrict Subinventories Code 
 Cum Manufacturing Lead Time Cumulative Total Lead Time  Bom Item Type Replenish To Order Flag Primary Uom Code Planning Make Buy Code  Fixed Lot Multiplier 
  Postprocessing Lead Time  Preprocessing Lead Time  Full Lead Time  Inventory Planning Code Min_Minmax_Quantity Max Minmax Quantity Minimum Order Quantity  
  Fixed Order Quantity Fixed Days Supply  Invoiceable Item Flag Invoice Enabled Flag Outside Operation Flag  Outside Operation Uom Type  Expense Account 
  Receiving_Subinventory Receiving Routing ID    Weight Uom  Unit Weight Volume Uom  Unit Volume Dimension Uom Length  Width Height 
  Sales Account Lamps Per Pack  Certification Needed  Certification Due Date  Certification Number  NPI Flag Use Approved Supplier 
  Default Buyer Allow Express Transactions  Container Container Type   Internal Volume Maximum Load Weight Long Description  Hazard Class Mir  UN Number Inventory Item Application  Fiscal Classification Code  Transaction Condition Class#


SELECT OOD.ORGANIZATION_CODE MASTER_ORG,MP.ORGANIZATION_CODE INVENTORY_ORGANIZATION_CODE,MSI.SEGMENT1,MSI.DESCRIPTION,MSI.INVENTORY_ITEM_STATUS_CODE,MSI.ITEM_TYPE,ENABLED_FLAG,
       MSI.PURCHASING_ITEM_FLAG, MSI.SHIPPABLE_ITEM_FLAG,MSI.CUSTOMER_ORDER_FLAG,MSI.INTERNAL_ORDER_FLAG,MSI.SERVICE_ITEM_FLAG,MSI.INVENTORY_ITEM_FLAG,MSI.INVENTORY_ASSET_FLAG,
       MSI.DEFAULT_INCLUDE_IN_ROLLUP_FLAG,MSI.COSTING_ENABLED_FLAG,MSI.COST_OF_SALES_ACCOUNT,MSI.PURCHASING_ENABLED_FLAG,MSI.CUSTOMER_ORDER_ENABLED_FLAG,MSI.INTERNAL_ORDER_ENABLED_FLAG,
       MSI.SO_TRANSACTIONS_FLAG,MSI.MTL_TRANSACTIONS_ENABLED_FLAG,MSI.STOCK_ENABLED_FLAG,MSI.BOM_ENABLED_FLAG,MSI.BUILD_IN_WIP_FLAG,MSI.REVISION_QTY_CONTROL_CODE,
       MSI.RETURNABLE_FLAG,MSI.ALLOW_ITEM_DESC_UPDATE_FLAG,MSI.INSPECTION_REQUIRED_FLAG,MSI.RECEIPT_REQUIRED_FLAG,MSI.RFQ_REQUIRED_FLAG,MSI.LIST_PRICE_PER_UNIT,
       MSI.PRICE_TOLERANCE_PERCENT,MSI.ROUNDING_FACTOR,MSI.LOT_CONTROL_CODE,MSI.AUTO_LOT_ALPHA_PREFIX,MSI.START_AUTO_LOT_NUMBER,NULL MATYRITY_DAYS,NULL HOLD_DAYS,
       NULL LOT_SPLIT_ENABLED,NULL LOT_TRANSLATE_ENABLED,NULL LOT_DIVISIBLE,NULL LOT_MERGE_ENABLED, NULL LOT_SUBSTITUTION_ENABLED,NULL BULK_PICKED,MSI.SHELF_LIFE_CODE,
       MSI.SHELF_LIFE_DAYS,MSI.SERIAL_NUMBER_CONTROL_CODE,MSI.SOURCE_TYPE,MSI.RESTRICT_SUBINVENTORIES_CODE,MSI.CUM_MANUFACTURING_LEAD_TIME,MSI.BOM_ITEM_TYPE,
       MSI.REPLENISH_TO_ORDER_FLAG,MSI.PRIMARY_UOM_CODE,MSI.PLANNING_MAKE_BUY_CODE,MSI.FIXED_LOT_MULTIPLIER,MSI.POSTPROCESSING_LEAD_TIME,MSI.PREPROCESSING_LEAD_TIME,
       MSI.FULL_LEAD_TIME,MSI.INVENTORY_PLANNING_CODE,MSI.MIN_MINMAX_QUANTITY,MSI.MAX_MINMAX_QUANTITY,MSI.MINIMUM_ORDER_QUANTITY,MSI.FIXED_ORDER_QUANTITY,MSI.FIXED_DAYS_SUPPLY,
       MSI.INVOICEABLE_ITEM_FLAG,MSI.INVOICE_ENABLED_FLAG,MSI.OUTSIDE_OPERATION_FLAG,MSI.OUTSIDE_OPERATION_UOM_TYPE,MSI.EXPENSE_ACCOUNT,NULL RECEIVING_SUBINVENTORY,
       MSI.RECEIVING_ROUTING_ID,MSI.WEIGHT_UOM_CODE,MSI.UNIT_WEIGHT,MSI.VOLUME_UOM_CODE,MSI.UNIT_VOLUME,NULL DIMENSION_UOM,NULL "LENGTH",NULL "WIDTH",NULL HEIGHT,
       MSI.SALES_ACCOUNT,NULL LAMPS_PER_PACK,NULL CERTIFICATION_NEEDED,NULL CERTIFICATION_DUE_DATE,NULL CERTIFICATION_NUMBER,NULL NPI_FLAG,MSI.MUST_USE_APPROVED_VENDOR_FLAG,
       MSI.BUYER_ID DEFALUT_BUYER,MSI.ALLOW_EXPRESS_DELIVERY_FLAG,MSI.CONTAINER_ITEM_FLAG,MSI.CONTAINER_TYPE_CODE,MSI.INTERNAL_VOLUME,MSI.MAXIMUM_LOAD_WEIGHT,
       NULL LONG_DESCRIPTION,MSI.HAZARD_CLASS_ID,MSI.UN_NUMBER_ID,NULL INVENTORY_ITEM_APPLICATION,NULL FISCAL_CLASSIFICATION_CODE,NULL TRANSACTION_CONDITION_CLASS
FROM MTL_SYSTEM_ITEMS_B MSI,
     MTL_PARAMETERS MP, 
     ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MP.MASTER_ORGANIZATION_ID = OOD.ORGANIZATION_ID
AND MSI.ORGANIZATION_ID = MP.ORGANIZATION_ID
AND MP.ORGANIZATION_CODE = 'C09'

