FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_AR_INV_PRINT_REP_CURRENCY.ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME="NPAR" LOOKUP_TYPE="BH_AR_INV_PRINT_REP_CURRENCY"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_AR_E_INVOICE_GEO.ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME="NPAR" LOOKUP_TYPE="BH_AR_E_INVOICE_GEO"


FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BH_INV_ITM_CONV.ldt PROGRAM APPLICATION_SHORT_NAME="NPCNV" CONCURRENT_PROGRAM_NAME="BH_INV_ITM_CONV"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BH_INV_ITM_CONV.ldt PROGRAM APPLICATION_SHORT_NAME="NPCNV" CONCURRENT_PROGRAM_NAME="BH_AP_INVOICE_CONV"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BH_AR_INVOICE_CONV.ldt PROGRAM APPLICATION_SHORT_NAME="NPCNV" CONCURRENT_PROGRAM_NAME="BH_AR_INVOICE_CONV"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct CLLPRTRN.ldt PROGRAM APPLICATION_SHORT_NAME="CLL" CONCURRENT_PROGRAM_NAME="CLLPRTRN"

FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct BHPRTRN.ldt - WARNING=YES UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BHPRTRN.ldt PROGRAM APPLICATION_SHORT_NAME="NPAR" CONCURRENT_PROGRAM_NAME="BHPRTRN"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BHCOPYFILE.ldt PROGRAM APPLICATION_SHORT_NAME="NPAR" CONCURRENT_PROGRAM_NAME="BHCOPYFILE"


FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_FILE_UPLOADER.ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME="NPAR" LOOKUP_TYPE="BH_FILE_UPLOADER"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_FILE_UPLOADER.ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME="NPAR" LOOKUP_TYPE="BH_AR_INV_PRINT_REP_CURRENCY"

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_FILE_UPLOADER.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BH_FILE_UPLOADER"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_CONVERSION_MODULES.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BH_CONVERSION_MODULES"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_CONVERSION_PROJECTS.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BH_CONVERSION_PROJECTS"
          
FNDLOAD apps/Ujk5dfGTizo 0 Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct NPFND_FNDLVMLU.ldt FUNCTION FUNCTION_NAME="NPFND_FNDLVMLU"
FNDLOAD apps/Ujk5dfGTizo 0 Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct NPFND_FILE_UPLOADER.ldt FUNCTION FUNCTION_NAME="NPFND_FILE_UPLOADER"


FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_AR_E_INVOICE_GEO.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE


FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BH_PE_DET_BANK_ACCT.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BH_PE_DET_BANK_ACCT"

FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_PE_DET_BANK_ACCT.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE

FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_CO_EBILLING_NOTES.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR__CO_EBILLING_NOTES_2.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR__CO_EBILLING_NOTES_3.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_CO_CTS.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_CO_LEG_CONTIN_TRANSAC.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE



NPGL_ONLINE_PL_PROC_DF

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_CO_DOC_SEQ_ADD_INFO.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BKR_AR_CO_DOC_SEQ_ADD_INFO"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_CO_EBILLING_NOTES.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BKR_AR_CO_EBILLING_NOTES"

FNDLOAD apps/Ujk5dfGTizo 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BH_AP_INV_CONV.ldt PROGRAM APPLICATION_SHORT_NAME="NPCNV" CONCURRENT_PROGRAM_NAME="BH_AP_INVOICE_CONV"


FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRARINV.ldt - WARNING=YES UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/Ujk5dfGTizo O Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRARINVWR.ldt - WARNING=YES UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE

FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_ARINVWR.ldt PROGRAM APPLICATION_SHORT_NAME="NPAR" CONCURRENT_PROGRAM_NAME="BKR_ARINVWR"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_ARINV.ldt PROGRAM APPLICATION_SHORT_NAME="NPAR" CONCURRENT_PROGRAM_NAME="BKR_ARINV"


FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_INV_CONTACT_DET.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BKR_AR_INV_CONTACT_DET"
FNDLOAD apps/Ujk5dfGTizo O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_AR_INV_BANK_FILTER.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BKR_AR_INV_BANK_FILTER"


FNDLOAD apps/Ujk5dfGTizo 0 Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct BKR_NPFND_FNDLVMLUPRJ.ldt FUNCTION FUNCTION_NAME="NPFND_FNDLVMLUPRJ"


FNDLOAD apps/thF4Qazsxp 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRGLPBPCDEFRECAST.ldt PROGRAM APPLICATION_SHORT_NAME="NPGL" CONCURRENT_PROGRAM_NAME="BKRGLPBPCDEFRECAST"
FNDLOAD apps/thF4Qazsxp 0 Y UPLOAD $ALR_TOP/patch/115/import/alr.lct BKRGLJOBREQALRT.ldt CUSTOM_MODE=FORCE



FNDLOAD apps/thF4Qazsxp 0 Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_PA_PBPC_DEF_RECAST_MATRIX.ldt FND_LOOKUP_TYPE LOOKUP_TYPE="BKR_PA_PBPC_DEF_RECAST_MATRIX"
FNDLOAD apps/thF4Qazsxp 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRGLPBPCDEFRECASTREP.ldt PROGRAM APPLICATION_SHORT_NAME="NPGL" CONCURRENT_PROGRAM_NAME="BKRGLPBPCDEFRECASTREP"
FNDLOAD apps/thF4Qazsxp 0 Y DOWNLOAD $ALR_TOP/patch/115/import/alr.lct BKRGLJEFAILALRT.ldt ALR_ALERTS APPLICATION_SHORT_NAME="NPGL" ALERT_NAME="BKR GL Journal Import Failure Alert"


FNDLOAD apps/<pass> 0 Y UPLOAD $ALR_TOP/patch/115/import/alr.lct BKRGLJEFAILALRT.ldt CUSTOM_MODE=FORCE

FNDLOAD apps/<pass> O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct BKR_PA_PBPC_DEF_RECAST_MATRIX.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE
FNDLOAD apps/<pass> O Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRGLPBPCDEFRECASTREP.ldt - WARNING=YES UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE


FNDLOAD apps/thF4Qazsxp 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKRGLPBPCDEFRECASTREP.ldt PROGRAM APPLICATION_SHORT_NAME="NPGL" CONCURRENT_PROGRAM_NAME="BKRGLPBPCDEFRECASTREP"


FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_NPCNV_ATTACHMENT_LOAD.ldt PROGRAM APPLICATION_SHORT_NAME="NPCNV" CONCURRENT_PROGRAM_NAME="BKR_NPCNV_ATTACHMENT_LOAD"

FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct NPINV_RERUN_SUBSTITUTE.ldt PROGRAM APPLICATION_SHORT_NAME="NPINV" CONCURRENT_PROGRAM_NAME="NPINV_RERUN_SUBSTITUTE"

FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_OM_PRICELIST_UPD_CP.ldt PROGRAM APPLICATION_SHORT_NAME="NPONT" CONCURRENT_PROGRAM_NAME="BKR_OM_PRICELIST_UPD"

FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_PO_CONV_STG_LOAD_CP.ldt PROGRAM APPLICATION_SHORT_NAME="NPPO" CONCURRENT_PROGRAM_NAME="BKR_PO_CONV_STG_LOAD"
FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_OM_CONV_HDR_STG_LOAD_CP.ldt PROGRAM APPLICATION_SHORT_NAME="NPOM" CONCURRENT_PROGRAM_NAME="BKR_OM_CONV_HDR_STG_LOAD"
FNDLOAD apps/<pass> 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct BKR_OM_CONV_LINES_STG_LOAD_CP.ldt PROGRAM APPLICATION_SHORT_NAME="NPOM" CONCURRENT_PROGRAM_NAME="BKR_OM_CONV_LINES_STG_LOAD"



FNDLOAD apps/<pass> O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct NPGL_ONLINE_PL_PROC_DF.ldt PROGRAM APPLICATION_SHORT_NAME="NPGL" CONCURRENT_PROGRAM_NAME="NPGL_ONLINE_PL_PROC_DF"