ALTER SESSION SET NLS_LANGUAGE= 'AMERICAN' NLS_TERRITORY= 'AMERICA' NLS_CURRENCY= '$' NLS_ISO_CURRENCY= 'AMERICA' NLS_NUMERIC_CHARACTERS= '.,' NLS_CALENDAR= 'GREGORIAN' NLS_DATE_FORMAT= 'DD-MON-RR' NLS_DATE_LANGUAGE= 'AMERICAN' NLS_SORT= 'BINARY'

ALTER SESSION SET  CURRENT_SCHEMA = APPS

SELECT *
FROM APPS.FND_LOOKUP_VALUES_VL
WHERE LOOKUP_TYPE = 'BKR_CST_CARVEOUT_CNV'