SELECT *
FROM APPS.FND_LOOKUP_VALUES_VL
WHERE Lookup_Type = 'NPIFS_TA_ASSIGNMENTS'


AND ATTRIBUTE1 IN (SELECT OHR_NUMBER
FROM
APPS.NPHXC_TIMECARDS_APPROVED_H H
WHERE PROJECT_NUMBER IN (SELECT SEGMENT1
                        FROM apps.PA_PROJECTS_ALL
                        WHERE org_id = 29564 --OU_AM_US
                        )
AND  H.PA_FLAG_DISCARD = 'RULE1:FSE EXCEPTION')       