SELECT HOU.ORGANIZATION_ID,HOU.NAME,HOU.SHORT_CODE,XEP.LEGAL_ENTITY_IDENTIFIER,XEP.NAME LE_NAME,GL.LEDGER_ID,GL.NAME,GL.SHORT_NAME,GL.DESCRIPTION,GL.CURRENCY_CODE
FROM HR_OPERATING_UNITS HOU,
     XLE_ENTITY_PROFILES XEP,
     GL_LEDGERS GL
WHERE HOU.DEFAULT_LEGAL_CONTEXT_ID =   XEP.LEGAL_ENTITY_ID
AND  HOU.SET_OF_BOOKS_ID = GL.LEDGER_ID

SELECY

LC3_EUR_IT_NP_GE(Ledger Id: 5)