ALTER SESSION SET NLS_LANGUAGE= 'AMERICAN' NLS_TERRITORY= 'AMERICA' NLS_CURRENCY= '$' NLS_ISO_CURRENCY= 'AMERICA' NLS_NUMERIC_CHARACTERS= '.,' NLS_CALENDAR= 'GREGORIAN' NLS_DATE_FORMAT= 'DD-MON-YYYY' NLS_DATE_LANGUAGE= 'AMERICAN' NLS_SORT= 'BINARY';
ALTER SESSION SET  CURRENT_SCHEMA = APPS;

SELECT  HOU.ORGANIZATION_ID,HOU.NAME,GL.LEDGER_ID,GL.NAME,GL.DESCRIPTION,FAV.APPLICATION_NAME,GPS.PERIOD_NAME,GPS.CLOSING_STATUS
FROM GL_PERIOD_STATUSES GPS,
             GL_LEDGERS GL,
             HR_OPERATING_UNITS HOU,
             FND_APPLICATION_VL FAV
WHERE GPS.LEDGER_ID = GL.LEDGER_ID
AND GL.LEDGER_ID = HOU.SET_OF_BOOKS_ID
AND GL.NAME IN ( 'LC3_USD_US_BKR','LC9_USD')
and FAV.APPLICATION_ID = GPS.APPLICATION_ID
AND HOU.NAME <> 'OU_AM_US_Dummy'
AND FAV.APPLICATION_NAME = 'General Ledger'
AND GPS.PERIOD_NAME IN ('JUL-23')
ORDER BY GPS.START_DATE DESC
