SELECT PLL.*
FROM  PO_HEADERS_ALL  PH,
              PO_LINES_ALL PL,
              PO_LINE_LOCATIONS_ALL PLL,
             PO_DISTRIBUTIONS_ALL PD
WHERE PH.PO_HEADER_ID = PL.PO_HEADER_ID
AND       PL.PO_LINE_ID = PD.PO_LINE_ID
AND       PL.PO_HEADER_ID = PLL.PO_HEADER_ID
AND       PL.PO_LINE_ID = PLL.PO_LINE_ID
AND      PH.SEGMENT1 = '6300000162-10'


SELECT *
FROM  PO_HEADERS_ALL  PH,
              PO_LINES_ALL PL
WHERE PH.PO_HEADER_ID = PL.PO_HEADER_ID
AND      PH.SEGMENT1 = '6300000162-10'


SELECT *
FROM  PO_HEADERS_ALL  PH,
              PO_LINES_ALL PL,
             PO_DISTRIBUTIONS_ALL PD
WHERE PH.PO_HEADER_ID = PL.PO_HEADER_ID
AND       PL.PO_LINE_ID = PD.PO_LINE_ID
AND      PH.SEGMENT1 = '6300000162-10'



select * 
from BKR_PO_HEADERS_INT_CNV
where document_num = '6300000162-10'

select * 
from BKR_PO_LINES_INT_CNV
where po_header_id = 2201846