INSERT INTO apps.BH_AR_INV_LINES_CONV_STG
      (interface_line_id,
       interface_line_context,
       interface_line_attribute1,
       interface_line_attribute2,
       interface_line_attribute3,
       interface_line_attribute4,
       interface_line_attribute5,
       interface_line_attribute6,
       interface_line_attribute7,
       interface_line_attribute8,
       batch_source_name,
       set_of_books_id,
       line_type,
       description,
       currency_code,
       amount,
       cust_trx_type_name,
       cust_trx_type_id,
       term_name,
       term_id,
       orig_system_batch_name,
       orig_system_bill_customer_ref,
       orig_system_bill_customer_id,
       orig_system_bill_address_ref,
       orig_system_bill_address_id,
       orig_system_bill_contact_ref,
       orig_system_bill_contact_id,
       orig_system_ship_customer_ref,
       orig_system_ship_customer_id,
       orig_system_ship_address_ref,
       orig_system_ship_address_id,
       orig_system_ship_contact_ref,
       orig_system_ship_contact_id,
       orig_system_sold_customer_ref,
       orig_system_sold_customer_id,
       link_to_line_id,
       link_to_line_context,
       link_to_line_attribute1,
       link_to_line_attribute2,
       link_to_line_attribute3,
       link_to_line_attribute4,
       link_to_line_attribute5,
       link_to_line_attribute6,
       link_to_line_attribute7,
       receipt_method_name,
       receipt_method_id,
       conversion_type,
       conversion_date,
       conversion_rate,
       customer_trx_id,
       trx_date,
       gl_date,
       document_number,
       trx_number,
       line_number,
       quantity,
       quantity_ordered,
       unit_selling_price,
       unit_standard_price,
       printing_option,
       interface_status,
       request_id,
       related_batch_source_name,
       related_trx_number,
       related_customer_trx_id,
       previous_customer_trx_id,
       credit_method_for_acct_rule,
       credit_method_for_installments,
       reason_code,
       tax_rate,
       tax_code,
       tax_precedence,
       exception_id,
       exemption_id,
       ship_date_actual,
       fob_point,
       ship_via,
       waybill_number,
       invoicing_rule_name,
       invoicing_rule_id,
       accounting_rule_name,
       accounting_rule_id,
       accounting_rule_duration,
       rule_start_date,
       primary_salesrep_number,
       primary_salesrep_id,
       sales_order,
       sales_order_line,
       sales_order_date,
       sales_order_source,
       sales_order_revision,
       purchase_order,
       purchase_order_revision,
       purchase_order_date,
       agreement_name,
       agreement_id,
       memo_line_name,
       memo_line_id,
       inventory_item_id,
       mtl_system_items_seg1,
       mtl_system_items_seg2,
       mtl_system_items_seg3,
       mtl_system_items_seg4,
       mtl_system_items_seg5,
       mtl_system_items_seg6,
       mtl_system_items_seg7,
       mtl_system_items_seg8,
       mtl_system_items_seg9,
       mtl_system_items_seg10,
       mtl_system_items_seg11,
       mtl_system_items_seg12,
       mtl_system_items_seg13,
       mtl_system_items_seg14,
       mtl_system_items_seg15,
       mtl_system_items_seg16,
       mtl_system_items_seg17,
       mtl_system_items_seg18,
       mtl_system_items_seg19,
       mtl_system_items_seg20,
       reference_line_id,
       reference_line_context,
       reference_line_attribute1,
       reference_line_attribute2,
       reference_line_attribute3,
       reference_line_attribute4,
       reference_line_attribute5,
       reference_line_attribute6,
       reference_line_attribute7,
       territory_id,
       territory_segment1,
       territory_segment2,
       territory_segment3,
       territory_segment4,
       territory_segment5,
       territory_segment6,
       territory_segment7,
       territory_segment8,
       territory_segment9,
       territory_segment10,
       territory_segment11,
       territory_segment12,
       territory_segment13,
       territory_segment14,
       territory_segment15,
       territory_segment16,
       territory_segment17,
       territory_segment18,
       territory_segment19,
       territory_segment20,
       attribute_category,
       attribute1,
       attribute2,
       attribute3,
       attribute4,
       attribute5,
       attribute6,
       attribute7,
       attribute8,
       attribute9,
       attribute10,
       attribute11,
       attribute12,
       attribute13,
       attribute14,
       attribute15,
       header_attribute_category,
       header_attribute1,
       header_attribute2,
       header_attribute3,
       header_attribute4,
       header_attribute5,
       header_attribute6,
       header_attribute7,
       header_attribute8,
       header_attribute9,
       header_attribute10,
       header_attribute11,
       header_attribute12,
       header_attribute13,
       header_attribute14,
       header_attribute15,
       comments,
       internal_notes,
       initial_customer_trx_id,
       ussgl_transaction_code_context,
       ussgl_transaction_code,
       acctd_amount,
       customer_bank_account_id,
       customer_bank_account_name,
       uom_code,
       uom_name,
       document_number_sequence_id,
       link_to_line_attribute10,
       link_to_line_attribute11,
       link_to_line_attribute12,
       link_to_line_attribute13,
       link_to_line_attribute14,
       link_to_line_attribute15,
       link_to_line_attribute8,
       link_to_line_attribute9,
       reference_line_attribute10,
       reference_line_attribute11,
       reference_line_attribute12,
       reference_line_attribute13,
       reference_line_attribute14,
       reference_line_attribute15,
       reference_line_attribute8,
       reference_line_attribute9,
       interface_line_attribute10,
       interface_line_attribute11,
       interface_line_attribute12,
       interface_line_attribute13,
       interface_line_attribute14,
       interface_line_attribute15,
       interface_line_attribute9,
       vat_tax_id,
       reason_code_meaning,
       last_period_to_credit,
       paying_customer_id,
       paying_site_use_id,
       tax_exempt_flag,
       tax_exempt_reason_code,
       tax_exempt_reason_code_meaning,
       tax_exempt_number,
       sales_tax_id,
       created_by,
       creation_date,
       last_updated_by,
       last_update_date,
       last_update_login,
       location_segment_id,
       movement_id,
       org_id,
       amount_includes_tax_flag,
       header_gdf_attr_category,
       header_gdf_attribute1,
       header_gdf_attribute2,
       header_gdf_attribute3,
       header_gdf_attribute4,
       header_gdf_attribute5,
       header_gdf_attribute6,
       header_gdf_attribute7,
       header_gdf_attribute8,
       header_gdf_attribute9,
       header_gdf_attribute10,
       header_gdf_attribute11,
       header_gdf_attribute12,
       header_gdf_attribute13,
       header_gdf_attribute14,
       header_gdf_attribute15,
       header_gdf_attribute16,
       header_gdf_attribute17,
       header_gdf_attribute18,
       header_gdf_attribute19,
       header_gdf_attribute20,
       header_gdf_attribute21,
       header_gdf_attribute22,
       header_gdf_attribute23,
       header_gdf_attribute24,
       header_gdf_attribute25,
       header_gdf_attribute26,
       header_gdf_attribute27,
       header_gdf_attribute28,
       header_gdf_attribute29,
       header_gdf_attribute30,
       line_gdf_attr_category,
       line_gdf_attribute1,
       line_gdf_attribute2,
       line_gdf_attribute3,
       line_gdf_attribute4,
       line_gdf_attribute5,
       line_gdf_attribute6,
       line_gdf_attribute7,
       line_gdf_attribute8,
       line_gdf_attribute9,
       line_gdf_attribute10,
       line_gdf_attribute11,
       line_gdf_attribute12,
       line_gdf_attribute13,
       line_gdf_attribute14,
       line_gdf_attribute15,
       line_gdf_attribute16,
       line_gdf_attribute17,
       line_gdf_attribute18,
       line_gdf_attribute19,
       line_gdf_attribute20,
       reset_trx_date_flag,
       payment_server_order_num,
       approval_code,
       address_verification_code,
       warehouse_id,
       translated_description,
       cons_billing_number,
       promised_commitment_amount,
       payment_set_id,
       original_gl_date,
       contract_line_id,
       contract_id,
       source_data_key1,
       source_data_key2,
       source_data_key3,
       source_data_key4,
       source_data_key5,
       invoiced_line_acctg_level,
       override_auto_accounting_flag,
       rule_end_date,
       mandate_last_trx_flag,
       source_application_id,
       source_event_class_code,
       source_entity_code,
       source_trx_id,
       source_trx_line_id,
       source_trx_line_type,
       source_trx_detail_tax_line_id,
       historical_flag,
       tax_regime_code,
       tax,
       tax_status_code,
       tax_rate_code,
       tax_jurisdiction_code,
       taxable_amount,
       taxable_flag,
       legal_entity_id,
       parent_line_id,
       deferral_exclusion_flag,
       payment_trxn_extension_id,
       payment_attributes,
       application_id,
       billing_date,
       trx_business_category,
       product_fisc_classification,
       product_category,
       product_type,
       line_intended_use,
       assessable_value,
       document_sub_type,
       default_taxation_country,
       user_defined_fisc_class,
       taxed_upstream_flag,
       payment_type_code,
       tax_invoice_date,
       tax_invoice_number,
       rev_rec_application,
       document_type_id,
       document_creation_date,
       doc_line_id_int_1,
       doc_line_id_int_2,
       doc_line_id_int_3,
       doc_line_id_int_4,
       doc_line_id_int_5,
       doc_line_id_char_1,
       doc_line_id_char_2,
       doc_line_id_char_3,
       doc_line_id_char_4,
       doc_line_id_char_5,
       source_term_name,
       source_cust_trx_type_name,
       SOURCE_CONVERSION_TYPE,
       SOURCE_TAX_RATE,
       SOURCE_TAX_CODE,
       SOURCE_ORIG_SYSTEM_BILL_CUSTOM,
       SOURCE_WAREHOUSE_ID,
       legacy_reference)
      (SELECT NULL, --interface_line_id,
              'CONVERSION_AUTOMATIC', --interface_line_context,
              TRANSACTION_NUMBER, --interface_line_attribute1,
              SALES_ORDER, --interface_line_attribute2,
              PURCHASE_ORDER, --interface_line_attribute3,
              Sunat_Doc_Num, --interface_line_attribute4,
              1, --interface_line_attribute5,
              NULL,  --interface_line_attribute6,
              NULL,  --interface_line_attribute7,
              NULL,  --interface_line_attribute8,
              'CONVERSION_AUTOMATIC', --batch_source_name,
              NULL, --set_of_books_id,
              'LINE', --line_type,
              MEMO_LINE_NAME,
              CURRENCY, --currency_code,
              OUTSTANDING_AMOUNT, --amount,
              TRANSACTION_TYPE_NAME, --cust_trx_type_name,
              NULL, --cust_trx_type_id,
              CASE WHEN OUTSTANDING_AMOUNT >=0 
                THEN PAYMENT_TERM
                  ELSE
                     NULL
               END CASE, --term_name,
              NULL, --term_id,
              NULL, --orig_system_batch_name,
              BILL_TO_SITE_REF, --orig_system_bill_customer_ref,
              NULL, --orig_system_bill_customer_id,
              NULL, --orig_system_bill_address_ref,
              NULL, --orig_system_bill_address_id,
              NULL, --orig_system_bill_contact_ref,
              NULL, --orig_system_bill_contact_id,
              NULL, --orig_system_ship_customer_ref,
              NULL, --orig_system_ship_customer_id,
              NULL, --orig_system_ship_address_ref,
              NULL, --orig_system_ship_address_id,
              NULL, --orig_system_ship_contact_ref,
              NULL, --orig_system_ship_contact_id,
              NULL, --orig_system_sold_customer_ref,
              NULL, --orig_system_sold_customer_id,
              NULL, --link_to_line_id,
              NULL, --link_to_line_context,
              NULL, --link_to_line_attribute1,
              NULL, --link_to_line_attribute2,
              NULL, --link_to_line_attribute3,
              NULL, --link_to_line_attribute4,
              NULL, --link_to_line_attribute5,
              NULL, --link_to_line_attribute6,
              NULL, --link_to_line_attribute7,
              NULL, --receipt_method_name,
              NULL, --receipt_method_id,
              'X', --conversion_type,
              RATE_DATE, --conversion_date,
              EXCHANGE_RATE, --conversion_rate,
              NULL, --customer_trx_id,
              TRANSACTION_DATE, --trx_date,
              GL_DATE, --gl_date,
              NULL, --document_number,
              TRANSACTION_NUMBER, --trx_number,
              LINE_NUMBER, --line_number,
              Quantity_Invoiced, --quantity,
              Quantity_Invoiced, --quantity_ordered,
              Unit_Selling_Price, --unit_selling_price,
              NULL, --unit_standard_price,
              NULL, --printing_option,
              NULL, --interface_status,
              1, --request_id,
              NULL, --related_batch_source_name,
              NULL, --related_trx_number,
              NULL, --related_customer_trx_id,
              NULL, --previous_customer_trx_id,
              NULL, --credit_method_for_acct_rule,
              NULL, --credit_method_for_installments,
              NULL, --reason_code,
              0, --tax_rate,
              'X', --tax_code,
              NULL, --tax_precedence,
              NULL, --exception_id,
              NULL, --exemption_id,
              Shipment_Date, --ship_date_actual,
              NULL, --fob_point,
              NULL, --ship_via,
              NULL, --waybill_number,
              NULL, --invoicing_rule_name,
              NULL, --invoicing_rule_id,
              NULL, --accounting_rule_name,
              NULL, --accounting_rule_id,
              NULL, --accounting_rule_duration,
              NULL, --rule_start_date,
              NULL, --primary_salesrep_number,
              NULL, --primary_salesrep_id,
              NULL, --sales_order,
              NULL, --sales_order_line,
              NULL, --sales_order_date,
              NULL, --sales_order_source,
              NULL, --sales_order_revision,
              NULL, --purchase_order,
              NULL, --purchase_order_revision,
              NULL, --purchase_order_date,
              NULL, --agreement_name,
              NULL, --agreement_id,
              NULL, --memo_line_name,
              NULL, --memo_line_id,
              NULL, --inventory_item_id,
              NULL, --mtl_system_items_seg1,
              NULL, --mtl_system_items_seg2,
              NULL, --mtl_system_items_seg3,
              NULL, --mtl_system_items_seg4,
              NULL, --mtl_system_items_seg5,
              NULL, --mtl_system_items_seg6,
              NULL, --mtl_system_items_seg7,
              NULL, --mtl_system_items_seg8,
              NULL, --mtl_system_items_seg9,
              NULL, --mtl_system_items_seg10,
              NULL, --mtl_system_items_seg11,
              NULL, --mtl_system_items_seg12,
              NULL, --mtl_system_items_seg13,
              NULL, --mtl_system_items_seg14,
              NULL, --mtl_system_items_seg15,
              NULL, --mtl_system_items_seg16,
              NULL, --mtl_system_items_seg17,
              NULL, --mtl_system_items_seg18,
              NULL, --mtl_system_items_seg19,
              NULL, --mtl_system_items_seg20,
              NULL, --reference_line_id,
              NULL, --reference_line_context,
              NULL, --reference_line_attribute1,
              NULL, --reference_line_attribute2,
              NULL, --reference_line_attribute3,
              NULL, --reference_line_attribute4,
              NULL, --reference_line_attribute5,
              NULL, --reference_line_attribute6,
              NULL, --reference_line_attribute7,
              NULL, --territory_id,
              NULL, -- territory_segment1,
              NULL, --territory_segment2,
              NULL, -- territory_segment3,
              NULL, -- territory_segment4,
              NULL, --territory_segment5,
              NULL, --territory_segment6,
              NULL, --territory_segment7,
              NULL, --territory_segment8,
              NULL, --territory_segment9,
              NULL, --territory_segment10,
              NULL, --territory_segment11,
              NULL, --territory_segment12,
              NULL, -- territory_segment13,
              NULL, --territory_segment14,
              NULL, --territory_segment15,
              NULL, --territory_segment16,
              NULL, --territory_segment17,
              NULL, --territory_segment18,
              NULL, --territory_segment19,
              NULL, -- territory_segment20,
              ATTRIBUTE_CATEGORY, --attribute_category,
              LINE_ATTRIBUTE1, --attribute1,
              LINE_ATTRIBUTE2, --attribute2,
              LINE_ATTRIBUTE3, --attribute3,
              LINE_ATTRIBUTE4, --attribute4,
              LINE_ATTRIBUTE5, --attribute5,
              LINE_ATTRIBUTE6, --attribute6,
              LINE_ATTRIBUTE7, --attribute7,
              LINE_ATTRIBUTE8, --attribute8,
              LINE_ATTRIBUTE9, --attribute9,
              LINE_ATTRIBUTE10, --attribute10,
              LINE_ATTRIBUTE11, --attribute11,
              LINE_ATTRIBUTE12, --attribute12,
              LINE_ATTRIBUTE13, --attribute13,
              LINE_ATTRIBUTE14, --attribute14,
              LINE_ATTRIBUTE15, --attribute15,
              HEADER_ATTRIBUTE_CATEGORY, --header_attribute_category,
              HEADER_ATTRIBUTE1, --header_attribute1,
              HEADER_ATTRIBUTE2, --header_attribute2,
              HEADER_ATTRIBUTE3, --header_attribute3,
              HEADER_ATTRIBUTE4, --header_attribute4,
              HEADER_ATTRIBUTE5, --header_attribute5,
              HEADER_ATTRIBUTE6, --header_attribute6,
              HEADER_ATTRIBUTE7, --header_attribute7,
              HEADER_ATTRIBUTE8, --header_attribute8,
              HEADER_ATTRIBUTE9, --header_attribute9,
              HEADER_ATTRIBUTE10, --header_attribute10,
              HEADER_ATTRIBUTE11, --header_attribute11,
              HEADER_ATTRIBUTE12, --header_attribute12,
              HEADER_ATTRIBUTE13, --header_attribute13,
              HEADER_ATTRIBUTE14, --header_attribute14,
              HEADER_ATTRIBUTE15, --header_attribute15,
              NULL, -- comments,
              NULL, -- internal_notes,
              NULL, -- initial_customer_trx_id,
              NULL, -- ussgl_transaction_code_context,
              NULL, -- ussgl_transaction_code,
              NULL, -- acctd_amount,
              NULL, -- customer_bank_account_id,
              NULL, -- customer_bank_account_name,
              UOM, --uom_code,
              NULL, -- uom_name,
              NULL, -- document_number_sequence_id,
              NULL, -- link_to_line_attribute10,
              NULL, -- link_to_line_attribute11,
              NULL, -- link_to_line_attribute12,
              NULL, -- link_to_line_attribute13,
              NULL, -- link_to_line_attribute14,
              NULL, -- link_to_line_attribute15,
              NULL, -- link_to_line_attribute8,
              NULL, -- link_to_line_attribute9,
              NULL, -- reference_line_attribute10,
              NULL, -- reference_line_attribute11,
              NULL, -- reference_line_attribute12,
              NULL, -- reference_line_attribute13,
              NULL, -- reference_line_attribute14,
              NULL, --  reference_line_attribute15,
              NULL, -- reference_line_attribute8,
              NULL, -- reference_line_attribute9,
              NULL, --  interface_line_attribute10,
              NULL, -- interface_line_attribute11,
              NULL, -- interface_line_attribute12,
              NULL, -- interface_line_attribute13,
              NULL, -- interface_line_attribute14,
              NULL, -- interface_line_attribute15,
              NULL, -- interface_line_attribute9,
              NULL, -- vat_tax_id,
              NULL, -- reason_code_meaning,
              NULL, -- last_period_to_credit,
              NULL, -- paying_customer_id,
              NULL, -- paying_site_use_id,
              NULL, -- tax_exempt_flag,
              NULL, -- tax_exempt_reason_code,
              NULL, -- tax_exempt_reason_code_meaning,
              NULL, -- tax_exempt_number,
              NULL, -- sales_tax_id,
              NULL, -- created_by,
              NULL, -- creation_date,
              NULL, -- last_updated_by,
              NULL, -- last_update_date,
              NULL, -- last_update_login,
              NULL, -- location_segment_id,
              NULL, -- movement_id,
              NULL, -- org_id,
              NULL, -- amount_includes_tax_flag,
              NULL, -- header_gdf_attr_category,
              NULL, -- header_gdf_attribute1,
              NULL, -- header_gdf_attribute2,
              NULL, -- header_gdf_attribute3,
              NULL, -- header_gdf_attribute4,
              NULL, -- header_gdf_attribute5,
              NULL, -- header_gdf_attribute6,
              NULL, -- header_gdf_attribute7,
              NULL, -- header_gdf_attribute8,
              NULL, -- header_gdf_attribute9,
              NULL, -- header_gdf_attribute10,
              NULL, -- header_gdf_attribute11,
              NULL, -- header_gdf_attribute12,
              NULL, -- header_gdf_attribute13,
              NULL, -- header_gdf_attribute14,
              NULL, -- header_gdf_attribute15,
              NULL, -- header_gdf_attribute16,
              NULL, -- header_gdf_attribute17,
              NULL, -- header_gdf_attribute18,
              NULL, -- header_gdf_attribute19,
              NULL, -- header_gdf_attribute20,
              NULL, -- header_gdf_attribute21,
              NULL, -- header_gdf_attribute22,
              NULL, -- header_gdf_attribute23,
              NULL, -- header_gdf_attribute24,
              NULL, -- header_gdf_attribute25,
              NULL, -- header_gdf_attribute26,
              NULL, -- header_gdf_attribute27,
              NULL, -- header_gdf_attribute28,
              NULL, -- header_gdf_attribute29,
              NULL, -- header_gdf_attribute30,
              NULL, -- line_gdf_attr_category,
              NULL, -- line_gdf_attribute1,
              NULL, -- line_gdf_attribute2,
              NULL, -- line_gdf_attribute3,
              NULL, -- line_gdf_attribute4,
              NULL, -- line_gdf_attribute5,
              NULL, -- line_gdf_attribute6,
              NULL, --  line_gdf_attribute7,
              NULL, -- line_gdf_attribute8,
              NULL, -- line_gdf_attribute9,
              NULL, -- line_gdf_attribute10,
              NULL, -- line_gdf_attribute11,
              NULL, -- line_gdf_attribute12,
              NULL, -- line_gdf_attribute13,
              NULL, --  line_gdf_attribute14,
              NULL, -- line_gdf_attribute15,
              NULL, -- line_gdf_attribute16,
              NULL, -- line_gdf_attribute17,
              NULL, -- line_gdf_attribute18,
              NULL, -- line_gdf_attribute19,
              NULL, -- line_gdf_attribute20,
              NULL, -- reset_trx_date_flag,
              NULL, -- payment_server_order_num,
              NULL, -- approval_code,
              NULL, -- address_verification_code,
              NULL, --  warehouse_id,
              NULL, -- translated_description,
              NULL, -- cons_billing_number,
              NULL, -- promised_commitment_amount,
              NULL, -- payment_set_id,
              NULL, -- original_gl_date,
              NULL, -- contract_line_id,
              NULL, -- contract_id,
              NULL, -- source_data_key1,
              NULL, -- source_data_key2,
              NULL, -- source_data_key3,
              NULL, -- source_data_key4,
              NULL, -- source_data_key5,
              NULL, -- invoiced_line_acctg_level,
              NULL, -- override_auto_accounting_flag,
              NULL, -- rule_end_date,
              NULL, -- mandate_last_trx_flag,
              NULL, -- source_application_id,
              NULL, -- source_event_class_code,
              NULL, -- source_entity_code,
              NULL, -- source_trx_id,
              NULL, -- source_trx_line_id,
              NULL, -- source_trx_line_type,
              NULL, -- source_trx_detail_tax_line_id,
              NULL, -- historical_flag,
              NULL, -- tax_regime_code,
              NULL, -- tax,
              NULL, -- tax_status_code,
              NULL, -- tax_rate_code,
              NULL, -- tax_jurisdiction_code,
              NULL, -- taxable_amount,
              NULL, -- taxable_flag,
              NULL, -- legal_entity_id,
              NULL, -- parent_line_id,
              NULL, -- deferral_exclusion_flag,
              NULL, --  payment_trxn_extension_id,
              NULL, -- payment_attributes,
              NULL, -- application_id,
              NULL, -- billing_date,
              NULL, -- trx_business_category,
              NULL, -- product_fisc_classification,
              NULL, --  product_category,
              NULL, -- product_type,
              NULL, -- line_intended_use,
              NULL, -- assessable_value,
              NULL, -- document_sub_type,
              NULL, -- default_taxation_country,
              NULL, -- user_defined_fisc_class,
              NULL, --  taxed_upstream_flag,
              NULL, --  payment_type_code,
              NULL, -- tax_invoice_date,
              NULL, -- tax_invoice_number,
              NULL, -- rev_rec_application,
              NULL, --  document_type_id,
              NULL, --  document_creation_date,
              NULL, --  doc_line_id_int_1,
              NULL, -- doc_line_id_int_2,
              NULL, -- doc_line_id_int_3,
              NULL, -- doc_line_id_int_4,
              NULL, -- doc_line_id_int_5,
              NULL, -- doc_line_id_char_1,
              NULL, --  doc_line_id_char_2,
              NULL, -- doc_line_id_char_3,
              NULL, -- doc_line_id_char_4,
              NULL, -- doc_line_id_char_5
              PAYMENT_TERM, --term_name,
              TRANSACTION_TYPE_NAME, --cust_trx_type_name,
              'X',--SOURCE_CONVERSION_TYPE,
              'X',--SOURCE_TAX_RATE,
              'X',--SOURCE_TAX_CODE,
              BILL_TO_SITE_REF,--   SOURCE_ORIG_SYSTEM_BILL_CUSTOM
              'X',--SOURCE_WAREHOUSE_ID
              TRANSACTION_NUMBER || '.' || '1'
         FROM apps.BH_AR_INV_LINES_CONV_DATA_ET)
