SELECT SYSDATE CURRENT_TIME
,ROUND((SYSDATE-VS.SQL_EXEC_START)*24*60,2) TIME_RUNNING_MINS
,CLIENT_IDENTIFIER
,VQL.SQL_FULLTEXT
,VS.*
,VQL.*
FROM GV$SESSION VS
,GV$SQL VQL
WHERE 1=1
AND VQL.INST_ID = VS.INST_ID
--AND VQL.SQL_ID = VS.PREV_SQL_ID
AND VQL.SQL_ID = VS.SQL_ID
AND VS.STATUS = 'ACTIVE'
AND TYPE <> 'BACKGROUND'
--and VS.SID = 3933
-- AND VS.MODULE LIKE '%OG_ADHOC_REPORT%'
--AND CLIENT_IDENTIFIER = '105065318'
ORDER BY VS.SQL_EXEC_START DESC,VS.SID;
