SELECT GIR.*
FROM APPS.GL_JE_LINES GJL,
     APPS.GL_IMPORT_REFERENCES GIR,
     APPS.XLA_AE_LINES XAL,
     APPS.XLA_AE_HEADERS XAH,
     APPS.XLA_EVENTS XE,
     APPS.XLA_TRANSACTION_ENTITIES XTE
WHERE  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
AND GIR.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
AND XAL.APPLICATION_ID = XAH.APPLICATION_ID
AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
AND XE.APPLICATION_ID = XAH.APPLICATION_ID
AND XE.EVENT_ID = XAH.EVENT_ID
AND XE.APPLICATION_ID = XTE.APPLICATION_ID
AND XE.ENTITY_ID = XTE.ENTITY_ID
AND XTE.ENTITY_ID = 13806966


SELECT *
FROM APPS.GL_JE_HEADERS
WHERE JE_HEADER_ID = 44176460
